### ISSUE TITLE
solo fiestas NACIONALES

### ISSUE THREAD

**Issue by sebastianet** [jdlopez/holydayapi#3]
Buenos dias - esta muy bien obtener las fiestas de una ciudad, pero a mi me interesa tener sololas fiestas nacionales.
Como puedo extraerlas ?

**Comment by jdlopez** [comment]
No hay un api directo, sólo está pensado para ciudades. Podrías filtrar los resultados por:
```
"country": "ES",
"type": "COUNTRY"
```

Pero me parece interesante y lo añado.

**Comment by jdlopez** [comment]
Agregada nueva versión con servicio:
https://holydayapi.herokuapp.com/holidays/country_code/es
Otra opción es pedir las vacaciones de una ciudad en la que no tengamos datos para municipio o para comunidad autónoma
