### ISSUE TITLE
¿No se incluyen los festivos locales para Madrid (28079)?

### ISSUE THREAD

**Issue by DLAcoding** [jdlopez/holydayapi#4]
Según el [fichero](https://datos.madrid.es/egob/catalogo/300082-2-calendario_laboral.xls) publicado del ayuntamiento de Madrid hay festivos locales los días 16 de mayo 2022 y 9 de noviembre de 2022 pero en la [respuesta de la API](https://holydayapi.herokuapp.com/holidays/city_code/28079/year/2022) no viene incluido. 

Parece que la llamada de Madrid trae sólo festividades Nacionales y de la Comunidad de Madrid.

Gracias por tu trabajo!

**Comment by jdlopez** [comment]
Efectivamente no estaban cargados los festivos de municipio Madrid. La bbdd de heroku que utilizo es la de pruebas y muy limitada por lo que cargo datos bajo petición.
Ya están cargados, gracias por avisar

**Comment by jdlopez** [comment]
Hay una página que resume las fiestas que están cargadas en el sistema:
https://holydayapi.herokuapp.com/status.html
