### ISSUE TITLE
Idea para tener hosting gratis ilimitado

### ISSUE THREAD

**Issue by psociety** [jdlopez/holydayapi#5]
Como no, es más fácil decirlo, que hacerlo pero:
1. Configurar Github Actions [es gratis para proyectos opensource] (https://github.com/actions/setup-java) para que ejecute el crawler al hacer un pull request por ejemplo o (si deja) 1 vez al año y guardar el output en el propio repositorio en formato json y/o sqlite
2. Añadir al repositorio un index.html + js que use el json
3. Usar Github Pages para que sea accesible,

Con esto no tienes la API como ahora, pero pasas a tener 2 vías que difícilmente caerán:
- La gente puede descargar el repo con los datos actualizados y procesarlos a gusto
- O bien tirar del Github Pages para descargar sólo lo que necesite mediante una UI.

**Comment by jdlopez** [comment]
Me ha costado un poco dar el paso pero al final he apañado algo parecido:
https://github.com/jdlopez/open-data
concretamente tengo los datos en este path:
https://github.com/jdlopez/open-data/tree/main/data/holidays/spain

No tengo app web para leer los datos para humanos, pero esa no era mi idea.
Gracias por la idea!
