### ISSUE TITLE
URL oficial de todos los festivos

### ISSUE THREAD

**Issue by ANTONIOPSD** [jdlopez/holydayapi#8]
Buenas, puedes sacar el CSV con todos los festivos desde la propia web de la seguridad social:

https://www.seg-social.es/wps/PA_POINCALAB/CalendarioServlet?exportacion=CSV&tipo=0

También se puede filtrar por provincia o población para que el csv sea más pequeño, pero vamos, que ocupa menos de 60kb el completo.

Esta es la página de usuario donde está todo:

https://www.seg-social.es/wps/portal/wss/internet/CalendarioLaboral

**Comment by jdlopez** [comment]
Muchas gracias!
Estoy poniendo los datos en: https://github.com/jdlopez/open-data
Intentaré ver como cargar estos porque veo que los municipios vienen "en letras" y siempre es más fastidiado de mapear

**Comment by jdlopez** [comment]
La voy a pasar a ese otro repo:
https://github.com/jdlopez/open-data/issues/1

**Comment by ANTONIOPSD** [comment]
Creo que puedes usar el tipo 1, que tiene el código de la provincia y la localidad, donde el código de la provincia son los 2 primeros números de los códigos postales:

https://www.seg-social.es/wps/PA_POINCALAB/CalendarioServlet?exportacion=CSV&tipo=1

Muestra:

COD_PROV,COD_LOC,FECHA,TIPO,DESCRIPCION
50,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
44,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
05,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
37,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
30,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
22,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
04,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
21,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
33,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
41,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
18,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
11,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
23,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
29,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
14,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
49,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
42,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
47,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
40,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
24,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
09,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
34,00,02-01-2023,1,"Lunes siguiente a Año Nuevo"
00,00,06-01-2023,0,"Epifanía del Señor"
30,300390000,07-01-2023,2,"Fiesta Local"
36,360620000,07-01-2023,2,"Fiesta Local"
50,500950000,14-01-2023,2,"Fiesta Local"
07,070060000,17-01-2023,2,"Fiesta Local"
07,070330000,17-01-2023,2,"Fiesta Local"
...

Listado de códigos de provincias:

https://www.ine.es/daco/daco42/codmun/cod_provincia.htm

Aquí están los diferentes listados que hay:

https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177031&menu=ultiDatos&idp=1254734710990

![imagen](https://github.com/jdlopez/holydayapi/assets/1978099/0bbac894-0137-4a9e-814a-9156464f904a)

**Comment by jdlopez** [comment]
En el cargador de vacaciones tengo un procesador de CSVs y lo he retocado un poco: 
https://github.com/jdlopez/open-data/blob/main/src/test/java/es/jdlopez/opendata/spain/TestHolidays.java

Dejo el fichero procesado en: https://github.com/jdlopez/open-data/blob/main/data/holidays/spain/2023.json
Cuando estén publicados los datos de 2024 lo cargaré también.

Gracias otra vez. Cualquier otra cosa mejor en la otra incidencia que esta la dejo cerrada
